{% set name = "cibuildwheel" %}
{% set version = "2.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pypa/cibuildwheel/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0fb6072b84c0dfa071c55f8f434523d22c34a599a6618752d6bcb2b8243b71cc

build:
  noarch: python
  entry_points:
    - cibuildwheel = cibuildwheel.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - hatchling
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - bashlex
    - bracex
    - filelock
    - platformdirs
    - click
    - pygithub
    - pyyaml
    - requests
    - rich >=9.6
    - packaging >=21.0
    - dependency-groups

test:
  imports:
    - cibuildwheel
  source_files:
    - test
  requires:
    - pip
    - jinja2
    - pytest >=6
    - pytest-timeout
    - pytest-xdist
    - python-build
    - validate-pyproject
    - python {{ python_min }}
  commands:
    - pip check
    - cibuildwheel --help
    # Only run a few tests that pass on local build
    - pytest test/test_dependency_versions.py
    - pytest test/test_emulation.py
    - pytest test/test_macos_archs.py
    - pytest test/test_wheel_tag.py
    - pytest test/test_windows.py


about:
  home: https://github.com/pypa/cibuildwheel
  summary: 'Building wheels across Mac, Linux, Windows, on multiple versions of Python.'
  description: |
    Python wheels are great. Building them across Mac, Linux, Windows,
    on multiple versions of Python, is not.
    cibuildwheel is here to help. cibuildwheel runs on your CI server -
    currently it supports GitHub Actions, Azure Pipelines, Travis CI, 
    AppVeyor, CircleCI, and GitLab CI - and it builds and tests your 
    wheels across all of your platforms.
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://cibuildwheel.pypa.io/en/stable/

extra:
  recipe-maintainers:
    - henryiii
    - MementoRC
